artifacts_root: artifacts  #creates artifacts folder


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/abhishek199677/MLOPS_Titanic_Project/raw/refs/heads/main/titanic.csv.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
